### ISSUE TITLE
This is not issue.I just need some help.

### ISSUE THREAD

**Issue by TiNredmc** [liposlt/HDSP#1]
Hello.I'm TinLethax.A long time ago I created the PD443X (as well should work in PD series of Infineon/SIEMENS/OSRAM OPTO.).SO I think can you help me test this library https://github.com/TiNredmc/PD443X_Lib 
Also I want to do colaboration with you for the HDSP2000/HCMS2000.Luckily it will arrive soon and I will get some hand on.

**Comment by liposlt** [comment]
> Hello.I'm TinLethax.A long time ago I created the PD443X (as well should work in PD series of Infineon/SIEMENS/OSRAM OPTO.).SO I think can you help me test this library https://github.com/TiNredmc/PD443X_Lib
> Also I want to do colaboration with you for the HDSP2000/HCMS2000.Luckily it will arrive soon and I will get some hand on.

Hi，I'll try to see if it works properly.I'm also glad to be able to test HDSP2000 with you.

**Comment by TiNredmc** [comment]
I just received my  HDSP 2000 today.It work well.so soon I will working on library.

**Comment by TiNredmc** [comment]
I also interesting to work on the STM8l too.

**Comment by liposlt** [comment]
> I just received my HDSP 2000 today.It work well.so soon I will working on library.

Congratulations!

**Comment by liposlt** [comment]
> I also interesting to work on the STM8l too.

I have not STM8, but I can try to work on STM32.

**Comment by TiNredmc** [comment]
I also have STM32. F3 disco and maple mini f103

**Comment by TiNredmc** [comment]
![20190125_140638](https://user-images.githubusercontent.com/18223668/51730995-175dd580-20ac-11e9-8afb-e65d980ba507.jpg)
![20190125_140626](https://user-images.githubusercontent.com/18223668/51731095-715e9b00-20ac-11e9-83d9-815228681ed0.jpg)

**Comment by TiNredmc** [comment]
This is my setup for the HCMS-2000 with STM8L151F3.I would like to use SDCC (Small Device C compiler)

**Comment by TiNredmc** [comment]
Hey.Did the font.h in HDSP2000 is for HDSP2000?
